In [1]:
import pandas as pd
import polars as pl

In [ ]:
df  = pl.read_csv("complaints/complaints.csv")
df.head()

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Date      ┆ Product   ┆ Sub-produ ┆ Issue     ┆ … ┆ Date sent ┆ Company   ┆ Timely    ┆ Complain │
│ received  ┆ ---       ┆ ct        ┆ ---       ┆   ┆ to        ┆ response  ┆ response? ┆ t ID     │
│ ---       ┆ str       ┆ ---       ┆ str       ┆   ┆ company   ┆ to        ┆ ---       ┆ ---      │
│ str       ┆           ┆ str       ┆           ┆   ┆ ---       ┆ consumer  ┆ str       ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-02-2 ┆ Vehicle   ┆ Loan      ┆ Strugglin ┆ … ┆ 2025-02-2 ┆ Closed    ┆ No        ┆ 12225144 │
│ 6T21:46:2 ┆ loan or   ┆           ┆ g to pay  ┆   ┆ 6T22:00:1 ┆ with expl ┆           ┆          │
│ 9.000Z    ┆ lease     ┆           ┆ your loan ┆   ┆ 6.000Z    ┆ anation   ┆           ┆          │
│ 2025-03-2 ┆ Debt coll ┆ Auto debt ┆ Communica ┆ … ┆ 2025-03-2 ┆ Closed    ┆ No        ┆ 12551969 │
│ 0T04:16:2 ┆ ection    ┆           ┆ tion      ┆   ┆ 0T04:25:0 ┆ with expl ┆           ┆          │
│ 3.000Z    ┆           ┆           ┆ tactics   ┆   ┆ 5.000Z    ┆ anation   ┆           ┆          │
│ 2025-04-2 ┆ Student   ┆ Federal   ┆ Strugglin ┆ … ┆ 2025-04-2 ┆ Closed    ┆ No        ┆ 13076106 │
│ 0T02:56:0 ┆ loan      ┆ student   ┆ g to      ┆   ┆ 0T03:04:3 ┆ with expl ┆           ┆          │
│ 9.000Z    ┆           ┆ loan      ┆ repay     ┆   ┆ 3.000Z    ┆ anation   ┆           ┆          │
│           ┆           ┆ servicing ┆ your loan ┆   ┆           ┆           ┆           ┆          │
│ 2025-04-1 ┆ Student   ┆ Federal   ┆ Dealing   ┆ … ┆ 2025-04-1 ┆ Closed    ┆ No        ┆ 13016738 │
│ 6T13:16:5 ┆ loan      ┆ student   ┆ with your ┆   ┆ 6T13:25:0 ┆ with expl ┆           ┆          │
│ 4.000Z    ┆           ┆ loan      ┆ lender or ┆   ┆ 5.000Z    ┆ anation   ┆           ┆          │
│           ┆           ┆ servicing ┆ se…       ┆   ┆           ┆           ┆           ┆          │
│ 2025-04-1 ┆ Student   ┆ Federal   ┆ Dealing   ┆ … ┆ 2025-04-1 ┆ Closed    ┆ No        ┆ 13015269 │
│ 6T20:39:2 ┆ loan      ┆ student   ┆ with your ┆   ┆ 6T20:54:4 ┆ with expl ┆           ┆          │
│ 2.000Z    ┆           ┆ loan      ┆ lender or ┆   ┆ 6.000Z    ┆ anation   ┆           ┆          │
│           ┆           ┆ servicing ┆ se…       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
df.shape

(15712797, 16)

In [22]:
for i in df['Product'].unique():
    print(i)

Credit card
Credit reporting or other personal consumer reports
Bank account or service
Debt or credit management
Money transfer, virtual currency, or money service
Virtual currency
Mortgage
Checking or savings account
Payday loan, title loan, personal loan, or advance loan
Payday loan, title loan, or personal loan
Credit card or prepaid card
Debt collection
Credit reporting
Student loan
Other financial service
Payday loan
Money transfers
Prepaid card
Consumer Loan
Vehicle loan or lease
Credit reporting, credit repair services, or other personal consumer reports

In [23]:
# Banking products only
BANKING_PRODUCTS = [
    "Student loan",
    "Credit card",
    "Bank account or service",
    "Mortgage",
    "Debt collection"
]

# Filter dataset
filtered_df = (
    df
    .filter(
        pl.col("Product").is_in(BANKING_PRODUCTS)
    )
    .filter(
        pl.col("Consumer complaint narrative").is_not_null()
    )
    .with_columns(
        pl.col("Consumer complaint narrative")
        .str.len_chars()
        .alias("n_chars")
    )
    .filter(
        pl.col("n_chars") >= 100
    )
)

print(filtered_df.shape)

(747899, 17)

In [24]:
filtered_df = filtered_df.with_columns([
    pl.col("Sub-product")
        .fill_null("Not specified"),

    pl.col("Sub-issue")
        .fill_null("Not specified")
])

In [25]:
filtered_df = filtered_df.select([
    "Consumer complaint narrative",
    "Product",
    "Sub-product",
    "Issue",
    "Sub-issue"
])

In [26]:
TARGET_PER_PRODUCT = 2000

sampled_df = (
    filtered_df
    .group_by("Product")
    .map_groups(
        lambda group:
        group.sample(
            n=min(len(group), TARGET_PER_PRODUCT),
            seed=42
        )
    )
)

In [27]:
sampled_df = (
    filtered_df
    .group_by(["Product", "Issue"])
    .map_groups(
        lambda group:
        group.sample(
            n=min(len(group), 200),
            seed=42
        )
    )
)

In [28]:
print(
    sampled_df
    .group_by("Product")
    .len()
    .sort("len", descending=True)
)

print(
    sampled_df
    .group_by("Issue")
    .len()
    .sort("len", descending=True)
)

shape: (5, 2)
┌─────────────────────────┬──────┐
│ Product                 ┆ len  │
│ ---                     ┆ ---  │
│ str                     ┆ u32  │
╞═════════════════════════╪══════╡
│ Credit card             ┆ 7304 │
│ Mortgage                ┆ 2803 │
│ Student loan            ┆ 2280 │
│ Debt collection         ┆ 2200 │
│ Bank account or service ┆ 1000 │
└─────────────────────────┴──────┘
shape: (78, 2)
┌─────────────────────────────────┬─────┐
│ Issue                           ┆ len │
│ ---                             ┆ --- │
│ str                             ┆ u32 │
╞═════════════════════════════════╪═════╡
│ Improper use of your report     ┆ 600 │
│ Problem with a company's inves… ┆ 600 │
│ Incorrect information on your … ┆ 600 │
│ Credit monitoring or identity … ┆ 460 │
│ Problem with a credit reportin… ┆ 400 │
│ …                               ┆ …   │
│ Balance transfer fee            ┆ 51  │
│ Cash advance                    ┆ 43  │
│ Cash advance fee                ┆ 41  │
│ Convenience checks              ┆ 37  │
│ Overlimit fee                   ┆ 30  │
└─────────────────────────────────┴─────┘

In [ ]:
sampled_df.write_csv(
    "Data/cfpb_banking_curated.csv"
)

In [18]:
import pandas as pd 
import polars as pl
import json

In [ ]:
sampled_df = pl.read_csv("Data/cfpb_banking_curated.csv")
sampled_df.head()

shape: (5, 5)
┌─────────────────────┬──────────┬─────────────────────┬─────────────────────┬─────────────────────┐
│ Consumer complaint  ┆ Product  ┆ Sub-product         ┆ Issue               ┆ Sub-issue           │
│ narrative           ┆ ---      ┆ ---                 ┆ ---                 ┆ ---                 │
│ ---                 ┆ str      ┆ str                 ┆ str                 ┆ str                 │
│ str                 ┆          ┆                     ┆                     ┆                     │
╞═════════════════════╪══════════╪═════════════════════╪═════════════════════╪═════════════════════╡
│ Navy Federal Credit ┆ Mortgage ┆ Conventional home   ┆ Problem with a      ┆ Investigation took  │
│ Union has …         ┆          ┆ mortgage            ┆ credit reportin…    ┆ more than 3…        │
│ On XX/XX/XXXX I     ┆ Mortgage ┆ Conventional home   ┆ Problem with a      ┆ Investigation took  │
│ emailed the Cu…     ┆          ┆ mortgage            ┆ credit reportin…    ┆ more than 3…        │
│ Loancare has failed ┆ Mortgage ┆ FHA mortgage        ┆ Problem with a      ┆ Their investigation │
│ to investi…         ┆          ┆                     ┆ credit reportin…    ┆ did not fi…         │
│ My mortgage         ┆ Mortgage ┆ Conventional home   ┆ Problem with a      ┆ Investigation took  │
│ payments were on a… ┆          ┆ mortgage            ┆ credit reportin…    ┆ more than 3…        │
│ I am writing to     ┆ Mortgage ┆ VA mortgage         ┆ Problem with a      ┆ Their investigation │
│ bring to your …     ┆          ┆                     ┆ credit reportin…    ┆ did not fi…         │
└─────────────────────┴──────────┴─────────────────────┴─────────────────────┴─────────────────────┘

In [20]:
sampled_df['Product'].unique()

shape: (5,)
Series: 'Product' [str]
[
	"Debt collection"
	"Credit card"
	"Student loan"
	"Mortgage"
	"Bank account or service"
]

In [21]:
import json
# Fill missing labels
sampled_df = sampled_df.with_columns([
    pl.col("Sub-product").fill_null("Not specified"),
    pl.col("Sub-issue").fill_null("Not specified")
])

SYSTEM_PROMPT = """
You are a banking complaint intake assistant.

Analyze the complaint narrative and identify:

1. Product
2. Sub-product
3. Issue
4. Sub-issue

Return JSON only.
"""

USER_TEMPLATE = """
Analyze the following customer complaint and determine the appropriate complaint classification.

Customer Complaint:
{complaint}
"""

samples = []

for row in sampled_df.iter_rows(named=True):

    assistant_output = {
        "product": row["Product"],
        "sub_product": row["Sub-product"],
        "issue": row["Issue"],
        "sub_issue": row["Sub-issue"]
    }

    sample = {
        "messages": [
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": USER_TEMPLATE.format(
        complaint=row["Consumer complaint narrative"]
    )
            },
            {
                "role": "assistant",
                "content": json.dumps(
                    assistant_output,
                    ensure_ascii=False
                )
            }
        ]
    }

    samples.append(sample)

In [22]:
from sklearn.model_selection import train_test_split

pdf = sampled_df.to_pandas()

In [15]:
train_df, temp_df = train_test_split(
    pdf,
    test_size=0.2,
    random_state=42,
    stratify=pdf["Product"]
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    random_state=42,
    stratify=temp_df["Product"]
)

In [24]:
def create_sample(row):

    assistant_output = {
        "product": row["Product"],
        "sub_product": row["Sub-product"],
        "issue": row["Issue"],
        "sub_issue": row["Sub-issue"]
    }

    return {
        "messages": [
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": USER_TEMPLATE.format(
        complaint=row["Consumer complaint narrative"]
    )
            },
            {
                "role": "assistant",
                "content": json.dumps(assistant_output)
            }
        ]
    }


def save_jsonl(df, path):

    with open(path, "w", encoding="utf-8") as f:

        for _, row in df.iterrows():

            sample = create_sample(row)

            f.write(
                json.dumps(sample, ensure_ascii=False)
                + "\n"
            )

In [ ]:
save_jsonl(train_df, "JSON_CHAT_TEMPLATE/train.jsonl")
save_jsonl(val_df, "JSON_CHAT_TEMPLATE/validation.jsonl")
save_jsonl(test_df, "JSON_CHAT_TEMPLATE/test.jsonl")